### ISSUE TITLE
Compiling problem

### ISSUE THREAD

**Issue by yuriv** [blackhole89/macros#1]
I think you need to import Data.Functor to `MacroProcessor.hs`

**Comment by blackhole89** [comment]
That's odd. What error message are you getting and what version of ghc are you using?

**Comment by yuriv** [comment]
Hi!

ghc version is:
The Glorious Glasgow Haskell Compilation System, version 7.6.3

The error message is:
[3 of 4] Compiling MacroProcessor   ( src/MacroProcessor.hs, build/MacroProcessor.o )

src/MacroProcessor.hs:231:53:
    Not in scope: `<$>'
    Perhaps you meant one of these:
      `<?>' (imported from Text.Parsec),
      `<|>' (imported from Text.Parsec)

src/MacroProcessor.hs:234:53:
    Not in scope: `<$>'
    Perhaps you meant one of these:
      `<?>' (imported from Text.Parsec),
      `<|>' (imported from Text.Parsec)

src/MacroProcessor.hs:237:59:
    Not in scope: `<$>'
    Perhaps you meant one of these:
      `<?>' (imported from Text.Parsec),
      `<|>' (imported from Text.Parsec)
make: *** [all] Error 1

But it doesn't matter, after importing Data.Functor it compiles and works fine. I have another question, could you add defining custom infix operators like in haskell? I am not familiar with parsec enough and can't to do it right now.

**Comment by blackhole89** [comment]
I see. For some reason, this import was not necessary in my version of ghc (8.0.2). I've added it now.

> I have another question, could you add defining custom infix operators  like in haskell? I am not familiar with parsec enough and can't to do it  right now.

This is actually a planned feature. I just need to figure out a good and efficient way to implement it, since operator definitions could presumably occur in the middle of a block and you would naively have to "reparse" everything after them (as the AST may change depending on the fixity and associativity desired). Really, I probably want to forbid some very pathological cases like
`int a @infixr 2 $x + $y { custom_add($x,$y) } + b + c`, where an operator is (re)defined in the middle of a running expression that includes it...
